In [31]:
# QUick and Easy Way (with xlwings)

# Install/Upgrade xlwings
!pip install xlwings --upgrade --quiet

In [32]:
# Import xlwings
import xlwings as xw

In [34]:
# Loads the selected cell(s) of the active workbook into a pandas DataFrame.
# If you don't have pandas installed, it returns the values as nested lists.
df_quick = xw.load(index=False)
df_quick

,Order ID,Returned,Remarks,Postal Code,None,Product ID,Category,None,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,None,None,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3.0,20%,5.4432
1,US-2017-156909,None,None,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2.0,30%,-1.0196
2,CA-2017-107727,None,None,07090,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3.0,20%,9.9468
3,CA-2017-120999,Yes,Need to check,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4.0,20%,16.5564
4,CA-2017-139619,None,None,01852,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2.0,20%,9.5616
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307,CA-2017-163629,None,None,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5.0,0%,55.6470
3308,CA-2017-121258,Yes,None,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2.0,0%,15.6332
3309,CA-2017-121258,Yes,None,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2.0,20%,19.3932
3310,CA-2017-121258,Yes,None,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4.0,0%,13.3200
3311,CA-2017-119914,None,None,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2.0,0%,72.9480

In [35]:
# Install libraries (if not installed yet)
# Openpyxl: Optional Pandas dependency to read/write Excel Files
!pip install pandas --quiet
!pip install openpyxl --quiet

In [37]:
import pandas as pd
from pathlib import Path

In [38]:
DATA_DIR = Path.cwd() / 'data'
file_path_messy_data = DATA_DIR / 'data_messy.xlsx'

In [43]:
df= pd.read_excel(file_path_messy_data)
df.head()

Empty DataFrame
Columns: []
Index: []

In [45]:
xl= pd.ExcelFile(file_path_messy_data)
xl.sheet_names

['Sheet1', 'Orders', 'Returns']

In [51]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,Business Transactions 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total Sales,Total Profit
3,NaN,NaN,NaN,Remarks from Jeff:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quick Summary:,733215.2552,12476
4,NaN,Order ID,Returned,Remarks,Postal Code,NaN,Product ID,Category,NaN,Product Name,Sales,Quantity,Discount,Profit,NaN,NaN,NaN,NaN

In [52]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders',
                  header=5)
df.head()

,Unnamed: 0,Order ID,Returned,Remarks,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,CA-2017-114412,NaN,NaN,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,20%,5.4432,NaN,NaN,NaN,NaN
1,NaN,US-2017-156909,NaN,NaN,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,30%,-1.0196,NaN,NaN,NaN,NaN
2,NaN,CA-2017-107727,NaN,NaN,7090.0,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,20%,9.9468,NaN,NaN,NaN,NaN
3,NaN,CA-2017-120999,Yes,Need to check,60540.0,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,20%,16.5564,NaN,NaN,NaN,NaN
4,NaN,CA-2017-139619,NaN,NaN,1852.0,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,20%,9.5616,NaN,NaN,NaN,NaN

In [54]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C, E:N')
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,20%,5.4432
1,US-2017-156909,NaN,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,30%,-1.0196
2,CA-2017-107727,NaN,7090.0,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,20%,9.9468
3,CA-2017-120999,Yes,60540.0,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,20%,16.5564
4,CA-2017-139619,NaN,1852.0,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,20%,9.5616

In [55]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C, E:N,',
                  true_values=['Yes']
                  )
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,20%,5.4432
1,US-2017-156909,NaN,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,30%,-1.0196
2,CA-2017-107727,NaN,7090.0,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,20%,9.9468
3,CA-2017-120999,True,60540.0,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,20%,16.5564
4,CA-2017-139619,NaN,1852.0,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,20%,9.5616

In [56]:
df.tail()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
3308,CA-2017-121258,True,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0%,15.6332
3309,CA-2017-121258,True,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,20%,19.3932
3310,CA-2017-121258,True,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0%,13.3200
3311,CA-2017-119914,NaN,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0%,72.9480
3312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,733215.2552,12476,NaN,93439.2696

In [57]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C, E:N,',
                   true_values=['Yes'],
                   skipfooter = 1
                  )
df.tail()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
3307,CA-2017-163629,NaN,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0%,55.6470
3308,CA-2017-121258,True,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0%,15.6332
3309,CA-2017-121258,True,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,20%,19.3932
3310,CA-2017-121258,True,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0%,13.3200
3311,CA-2017-119914,NaN,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0%,72.9480

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      3312 non-null   object
 1   Returned      288 non-null    object
 2   Postal Code   3312 non-null   int64
 3   Unnamed: 5    3312 non-null   object
 4   Product ID    3312 non-null   object
 5   Category      3312 non-null   object
 6   Unnamed: 8    3312 non-null   object
 7   Product Name  3312 non-null   object
 8   Sales         3312 non-null   float64
 9   Quantity      3312 non-null   int64
 10  Discount      3312 non-null   object
 11  Profit        3312 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 310.6+ KB

In [59]:
df['Discount'].iloc[0]

'20%'

In [60]:
type(df['Discount'].iloc[0])

str

In [62]:
discount = '20%'
discount = discount.replace('%','')
discount = float(discount)/100
discount

0.2

In [63]:
def convert_discount(row):
    '''Convert string (%) to float'''
    pct_value = row.replace('%','')
    pct_value = float(pct_value)/100
    return pct_value

In [65]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C, E:N,',
                   true_values=['Yes'],
                   skipfooter = 1,
                   converters={'Discount': convert_discount}
                  )
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
1,US-2017-156909,NaN,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
2,CA-2017-107727,NaN,7090,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
3,CA-2017-120999,True,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,CA-2017-139619,NaN,1852,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,0.2,9.5616

In [66]:
df = pd.read_excel(file_path_messy_data,
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C, E:N,',
                   true_values=['Yes'],
                   skipfooter = 1,
                   converters={'Discount': convert_discount},
                   dtype={'Postal Code': 'object'}
                  )
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
1,US-2017-156909,NaN,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
2,CA-2017-107727,NaN,07090,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
3,CA-2017-120999,True,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,CA-2017-139619,NaN,01852,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,0.2,9.5616

In [67]:
df.fillna(False, inplace=True)
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,False,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
1,US-2017-156909,False,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
2,CA-2017-107727,False,07090,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
3,CA-2017-120999,True,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,CA-2017-139619,False,01852,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,0.2,9.5616

In [69]:
df = df.rename(columns={"Unnamed: 5": "Region",
                      "Unnamed: 8": "Sub-Category"})
df.head()

,Order ID,Returned,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,False,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
1,US-2017-156909,False,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
2,CA-2017-107727,False,07090,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
3,CA-2017-120999,True,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,CA-2017-139619,False,01852,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,0.2,9.5616

In [71]:
df.drop_duplicates(inplace=True)

In [72]:
file_path_cleaned_data = DATA_DIR / 'data_cleaned.xlsx'

In [74]:
df.to_excel(file_path_cleaned_data,
            sheet_name='Cleaned_Data',
            index=False)